import os
import re
import csv

path='./gpbsa'
add=open('./gpbsa.csv','w')
addWriter=csv.writer(add)

d=['id','GC-vdw','GC-ele','GC-gb','GC-sa','GL-vdw','GL-ele','GL-gb','GL-sa','GP-vdw','GP-ele','GP-gb','GP-sa','GA-vdw','GA-ele','GA-gb','GA-sa','GTotal','PC-vdw','PC-ele','PC-Pb','PC-sa','PC-di','PL-vdw','PL-ele','PL-pb','PL-sa','PL-di','PP-vdw','PP-ele','PP-pb','PP-sa','PP-di','PA-vdw','PA-ele','PA-pb','PA-sa','PA-di','PTotal']
addWriter.writerow(d)

for filename in os.listdir(path):
    final=re.compile(r'_FINAL_RESULTS_MMPBSA.dat')
    mo=final.search(filename)
    if mo!=None:
        line=[]
        id=filename[:-25]
        #print(id)
        file1=open(os.path.join(path,filename))
        content=file1.read()
        #print(content)
        #try:
        GB=re.compile(r'GENERALIZED BORN:.*?POISSON BOLTZMANN:',re.DOTALL)
        GB1=GB.search(content).group()
        complex=re.compile(r'Complex:.*?TOTAL',re.DOTALL)
        complex1=complex.search(GB1).group()
        v=re.compile(r'VDWAALS\s+\S+')
        v1=v.search(complex1).group()
        v2=re.compile(r'\s\S+')
        v3=v2.search(v1).group()[1:]
        #print(v3)
        e=re.compile(r'EEL\s+\S+')
        e1=e.search(complex1).group()
        e2=re.compile(r'\s\S+')
        e3=e2.search(e1).group()[1:]
        g=re.compile(r'EGB\s+\S+')
        g1=g.search(complex1).group()
        g2=re.compile(r'\s\S+')
        g3=g2.search(g1).group()[1:]
        s=re.compile(r'ESURF\s+\S+')
        s1=s.search(complex1).group()
        s2=re.compile(r'\s\S+')
        s3=s2.search(s1).group()[1:]
        #print(v3,' ',e3,' ',g3,' ',s3)
        #print(complex1.group())
        ligand=re.compile(r'Ligand:.*?TOTAL',re.DOTALL)
        ligand1=ligand.search(GB1).group()
        vv=re.compile(r'VDWAALS\s+\S+')
        vv1=vv.search(ligand1).group()
        vv2=re.compile(r'\s\S+')
        vv3=vv2.search(vv1).group()[1:]
        ee=re.compile(r'EEL\s+\S+')
        ee1=ee.search(ligand1).group()
        ee2=re.compile(r'\s\S+')
        ee3=ee2.search(ee1).group()[1:]
        gg=re.compile(r'EGB\s+\S+')
        gg1=gg.search(ligand1).group()
        gg2=re.compile(r'\s\S+')
        gg3=gg2.search(gg1).group()[1:]
        ss=re.compile(r'ESURF\s+\S+')
        ss1=ss.search(ligand1).group()
        ss2=re.compile(r'\s\S+')
        ss3=ss2.search(ss1).group()[1:]
        #print(vv3,' ',ee3,' ',gg3,' ',ss3)
        protein=re.compile(r'Receptor:.*?TOTAL',re.DOTALL)
        protein1=protein.search(GB1).group()
        vvv=re.compile(r'VDWAALS\s+\S+')
        vvv1=vvv.search(protein1).group()
        vvv2=re.compile(r'\s\S+')
        vvv3=vvv2.search(vvv1).group()[1:]
        eee=re.compile(r'EEL\s+\S+')
        eee1=eee.search(protein1).group()
        eee2=re.compile(r'\s\S+')
        eee3=eee2.search(eee1).group()[1:]
        ggg=re.compile(r'EGB\s+\S+')
        ggg1=ggg.search(protein1).group()
        ggg2=re.compile(r'\s\S+')
        ggg3=ggg2.search(ggg1).group()[1:]
        sss=re.compile(r'ESURF\s+\S+')
        sss1=sss.search(protein1).group()
        sss2=re.compile(r'\s\S+')
        sss3=sss2.search(sss1).group()[1:]
        #print(vvv3,' ',eee3,' ',ggg3,' ',sss3)
        all=re.compile(r'Differences.*?TOTAL',re.DOTALL)
        all1=all.search(GB1).group()
        vvvv=re.compile(r'VDWAALS\s+\S+')
        vvvv1=vvvv.search(all1).group()
        vvvv2=re.compile(r'\s\S+')
        vvvv3=vvvv2.search(vvvv1).group()[1:]
        eeee=re.compile(r'EEL\s+\S+')
        eeee1=eeee.search(all1).group()
        eeee2=re.compile(r'\s\S+')
        eeee3=eeee2.search(eeee1).group()[1:]
        gggg=re.compile(r'EGB\s+\S+')
        gggg1=gggg.search(all1).group()
        gggg2=re.compile(r'\s\S+')
        gggg3=gggg2.search(gggg1).group()[1:]
        ssss=re.compile(r'ESURF\s+\S+')
        ssss1=sss.search(all1).group()
        ssss2=re.compile(r'\s\S+')
        ssss3=ssss2.search(ssss1).group()[1:]
        line.append(id)
        line.append(v3)
        line.append(e3)
        line.append(g3)
        line.append(s3)
        line.append(vv3)
        line.append(ee3)
        line.append(gg3)
        line.append(ss3)
        line.append(vvv3)
        line.append(eee3)
        line.append(ggg3)
        line.append(sss3)
        line.append(vvvv3)
        line.append(eeee3)
        line.append(gggg3)
        line.append(ssss3)
        total=round(float(vvvv3)+float(eeee3)+float(gggg3)+float(ssss3),4)
        line.append(total)
        PB=re.compile(r'POISSON BOLTZMANN:.*?-------------------------------------------------------------------------------\n-------------------------------------------------------------------------------',re.DOTALL)
        PB1=PB.search(content).group()
        complex=re.compile(r'Complex:.*?TOTAL',re.DOTALL)
        complex1=complex.search(PB1).group()
        v=re.compile(r'VDWAALS\s+\S+')
        v1=v.search(complex1).group()
        v2=re.compile(r'\s\S+')
        v3=v2.search(v1).group()[1:]
        #print(v3)
        e=re.compile(r'EEL\s+\S+')
        e1=e.search(complex1).group()
        e2=re.compile(r'\s\S+')
        e3=e2.search(e1).group()[1:]
        g=re.compile(r'EPB\s+\S+')
        g1=g.search(complex1).group()
        g2=re.compile(r'\s\S+')
        g3=g2.search(g1).group()[1:]
        s=re.compile(r'ENPOLAR\s+\S+')
        s1=s.search(complex1).group()
        s2=re.compile(r'\s\S+')
        s3=s2.search(s1).group()[1:]
        di=re.compile(r'EDISPER\s+\S+')
        di1=di.search(complex1).group()
        di2=re.compile(r'\s\S+')
        di3=di2.search(di1).group()[1:]
        #print(v3,' ',e3,' ',g3,' ',s3)
        #print(complex1.group())
        ligand=re.compile(r'Ligand:.*?TOTAL',re.DOTALL)
        ligand1=ligand.search(PB1).group()
        vv=re.compile(r'VDWAALS\s+\S+')
        vv1=vv.search(ligand1).group()
        vv2=re.compile(r'\s\S+')
        vv3=vv2.search(vv1).group()[1:]
        ee=re.compile(r'EEL\s+\S+')
        ee1=ee.search(ligand1).group()
        ee2=re.compile(r'\s\S+')
        ee3=ee2.search(ee1).group()[1:]
        gg=re.compile(r'EPB\s+\S+')
        gg1=gg.search(ligand1).group()
        gg2=re.compile(r'\s\S+')
        gg3=gg2.search(gg1).group()[1:]
        ss=re.compile(r'ENPOLAR\s+\S+')
        ss1=ss.search(ligand1).group()
        ss2=re.compile(r'\s\S+')
        ss3=ss2.search(ss1).group()[1:]
        dii=re.compile(r'EDISPER\s+\S+')
        dii1=dii.search(ligand1).group()
        dii2=re.compile(r'\s\S+')
        dii3=dii2.search(dii1).group()[1:]
        #print(vv3,' ',ee3,' ',gg3,' ',ss3)
        protein=re.compile(r'Receptor:.*?TOTAL',re.DOTALL)
        protein1=protein.search(PB1).group()
        vvv=re.compile(r'VDWAALS\s+\S+')
        vvv1=vvv.search(protein1).group()
        vvv2=re.compile(r'\s\S+')
        vvv3=vvv2.search(vvv1).group()[1:]
        eee=re.compile(r'EEL\s+\S+')
        eee1=eee.search(protein1).group()
        eee2=re.compile(r'\s\S+')
        eee3=eee2.search(eee1).group()[1:]
        ggg=re.compile(r'EPB\s+\S+')
        ggg1=ggg.search(protein1).group()
        ggg2=re.compile(r'\s\S+')
        ggg3=ggg2.search(ggg1).group()[1:]
        sss=re.compile(r'ENPOLAR\s+\S+')
        sss1=sss.search(protein1).group()
        sss2=re.compile(r'\s\S+')
        sss3=sss2.search(sss1).group()[1:]
        diii=re.compile(r'EDISPER\s+\S+')
        diii1=diii.search(protein1).group()
        diii2=re.compile(r'\s\S+')
        diii3=diii2.search(diii1).group()[1:]
        #print(vvv3,' ',eee3,' ',ggg3,' ',sss3)
        all=re.compile(r'Differences.*?TOTAL',re.DOTALL)
        all1=all.search(PB1).group()
        vvvv=re.compile(r'VDWAALS\s+\S+')
        vvvv1=vvvv.search(all1).group()
        vvvv2=re.compile(r'\s\S+')
        vvvv3=vvvv2.search(vvvv1).group()[1:]
        eeee=re.compile(r'EEL\s+\S+')
        eeee1=eeee.search(all1).group()
        eeee2=re.compile(r'\s\S+')
        eeee3=eeee2.search(eeee1).group()[1:]
        gggg=re.compile(r'EPB\s+\S+')
        gggg1=gggg.search(all1).group()
        gggg2=re.compile(r'\s\S+')
        gggg3=gggg2.search(gggg1).group()[1:]
        ssss=re.compile(r'ENPOLAR\s+\S+')
        ssss1=sss.search(all1).group()
        ssss2=re.compile(r'\s\S+')
        ssss3=ssss2.search(ssss1).group()[1:]
        diiii=re.compile(r'EDISPER\s+\S+')
        diiii1=diiii.search(all1).group()
        diiii2=re.compile(r'\s\S+')
        diiii3=diiii2.search(diiii1).group()[1:]
        line.append(v3)
        line.append(e3)
        line.append(g3)
        line.append(s3)
        line.append(di3)
        line.append(vv3)
        line.append(ee3)
        line.append(gg3)
        line.append(ss3)
        line.append(dii3)
        line.append(vvv3)
        line.append(eee3)
        line.append(ggg3)
        line.append(sss3)
        line.append(diii3)
        line.append(vvvv3)
        line.append(eeee3)
        line.append(gggg3)
        line.append(ssss3)
        line.append(diiii3)
        total=round(float(vvvv3)+float(eeee3)+float(gggg3)+float(ssss3)+float(diiii3),4)
        line.append(total)
        addWriter.writerow(line)
        #except:
            #print(id+' ')
add.close()
